# Generated by Django 3.0 on 2019-12-10 21:49

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[customers.models.validate_phone_number])),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('address_text', models.CharField(max_length=250)),
                ('rate', models.FloatField(default=0.0)),
                ('craft', models.IntegerField(choices=[(1, 'Carpentry'), (2, 'Electrical'), (3, 'Plumbing')], default=0)),
                ('available_today', models.BooleanField(default=True)),
                ('available_now', models.BooleanField(default=True)),
                ('user_type', models.BooleanField(default=True)),
            ],
        ),
    ]
